version: '2.0'
services:
  elasticsearch_hq:
    image: elastichq/elasticsearch-hq:release-v3.4.1
    ports:
      - "5000:5000"
    environment:
      - HQ_DEFAULT_URL=http://es_master:9200
    networks:
      - esnet

  es_master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - esnet

  es_node:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - "discovery.zen.ping.unicast.hosts=es_master"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://es_master:9200
    networks:
      - esnet

#  metricbeat:
#    image: docker.elastic.co/beats/metricbeat:6.4.0
#    volumes:
#      - /proc:/hostfs/proc:ro
#      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
#      - /:/hostfs:ro
#      - /vagrant/app/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
#    environment:
#      - ES_HOSTS=192.168.56.101
#    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:
